### ISSUE TITLE
This code doesn't work anymore as the Interface is changed

### ISSUE THREAD

**Issue by gow2613** [MysticBytes786/Brute-force-metamask#1]
This code doesn't work because #metamask changed their user interface and the XPath doesn't work

**Comment by 0xFMD** [comment]
Hi, I'm no longer actively maintaining this project. However, if you're interested in making fixes or improvements, please feel free to fork it or submit a PR.

**Comment by 0x00032** [comment]
> This code doesn't work because #metamask changed their user interface and the XPath doesn't work

I just opened a pull request to update it for ya!
